-- Рейтинг (Спринт 12)
CREATE TABLE IF NOT EXISTS rating_MPA (
    mpa_id SERIAL NOT NULL PRIMARY KEY,
    mpa_name VARCHAR NOT NULL
);

-- Фильмы (Спринт 12)
CREATE TABLE IF NOT EXISTS films (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR,
    release_date TIMESTAMP,
    duration BIGINT,
    rating_id INT NOT NULL REFERENCES rating_MPA(mpa_id) ON DELETE RESTRICT
);

-- Жанры (Спринт 12)
CREATE TABLE IF NOT EXISTS genres (
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL
);

-- Жанры - Фильмы (Спринт 12)
CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    genre_id INT NOT NULL REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

-- Пользователи (Спринт 12)
CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    email VARCHAR NOT NULL,
    login VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    birthday TIMESTAMP
);

-- Друзья (Спринт 12)
CREATE TABLE IF NOT EXISTS user_friends (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    friend_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);

-- Лайки (Спринт 12)
CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    user_liked_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_liked_id)
);

-- Функциональность "Отзывы" (Спринт 13)
CREATE TABLE IF NOT EXISTS reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT(1000) NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    film_id BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    useful INT NOT NULL DEFAULT 0
);

-- Функциональность Лайки / Дислайки (Спринт 13)
CREATE TABLE IF NOT EXISTS review_likes (
    review_id BIGINT NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_like BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id)
);